version: '3'

services:
  app:
    image: 'calendso/calendso:latest'
    restart: always
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    ports:
      - '${PORT}:3000'

  db:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - CALENDSO_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=${APP_URL}
      - BASE_URL=${APP_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: