version: '3'

services:
  app:
    image: 'fireflyiii/core'
    environment:
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_DATABASE=firefly_money
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASS}
      - DB_PORT=3306
      - DB_USERNAME=${DB_USER}
      - MAPBOX_API_KEY=${MAPBOX_KEY}
    restart: always
    volumes:
      - app_uploads:/var/www/html/storage/upload

  db:
    image: 'mysql'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=firefly_money
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_uploads:
  db_data:
